BACKLOG-21210 : make sam works with jahia 8.2
Jahia/server-availability-manager pull request #86
Opened 2023-06-23 08:37 UTC by dgriffon

Following that change 
https://github.com/Jahia/jahia/blob/89aee45eb701dfa77e584376f6484314b1d4f0ca/jahia-parent/pom.xml#L73
the version range of `org.apache.jackrabbit.api` has been set to 1

Changing the parent version fixes the dependency issue

2023-06-23 08:56 UTC, Fgerthoffert requested changes
Updating jahia parent should be a last resort option for addressing this issue, and if we were to do that, we would need to update SAM first digit (SAM 3x)

2023-06-26 11:36 UTC, gflores-jahia commented
Seems only solution for now is to update parent version. See following comments https://jira.jahia.org/browse/BACKLOG-21210?focusedCommentId=151593&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-151593

2023-06-26 12:18 UTC, Fgerthoffert approved these changes

2023-06-27 07:43 UTC, dgriffon commented
fixed on Jahia core side
Now run is OK https://github.com/Jahia/server-availability-manager/actions/runs/5384253723

2023-06-27 07:43 UTC, closed without merging